site_name: pfsense-api-client
theme:
  name: material
plugins:
- search:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    watch:
    - pfsense_api_client/
nav:
- Home: README.md
- API Documentation: api.md
repo_name: yaleman/pfsense-api-client
repo_url: https://github.com/yaleman/pfsense-api-client
site_url: https://yaleman.github.io/pfsense-api-client/
