name: MKDocs Deployment to GitHub Pages

"on":
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base mkdocstrings
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: docs/requirements.txt
